Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Style/ClassVars:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/ConditionalAssignment:
  Enabled: false

Metrics/MethodLength:
  Max: 24

Style/GuardClause:
  Enabled: false

Metrics/ClassLength:
  Max: 181

Metrics/BlockLength:
  Max: 29
